### PR TITLE
refactor: rename full to content

### LINKED ISSUE #8: Rename full.html to content.html
"full" is referring to a test page for the tracking protection list that contains the Content category. This page tests a gravatar resource, which is on the Content category.

### PR DESCRIPTION
**Pull request by rpappalax**
Closes #8

### CODE REVIEW

**Comment by rpappalax** [comment]
looks like I don't have permission to add a reviewer:  r?  @englehardt @groovecoder

**Comment by groovecoder** [comment]
Assigning to @englehardt 😜

**Comment by englehardt** [comment]
@rpappalax Mind to update the filename in `README.md` as well?

```
### https://mozilla.github.io/tracking-test/full.html
1. Create a STRICT profile
2. Restart browser
3. Navigate to https://mozilla.github.io/tracking-test/full.html

expected result: fox displays, confirming page is serving correct content
```

**Comment by rpappalax** [comment]
> @rpappalax Mind to update the filename in `README.md` as well?
> 
> ```
> ### https://mozilla.github.io/tracking-test/full.html
> 1. Create a STRICT profile
> 2. Restart browser
> 3. Navigate to https://mozilla.github.io/tracking-test/full.html
> 
> expected result: fox displays, confirming page is serving correct content
> ```

done, thanks!

**Review by englehardt — APPROVED** [review]

**Pull request merged**
